name: Build and Push Container

on:
  push: { branches: [ master ] }
  pull_request: { branches: [ master ] }

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - uses: coursier/cache-action@v6.4
      - uses: VirtusLab/scala-cli-setup@v1.5
      - run: |
          scala-cli \
            --power package \
            --jvm 24 \
            --project-version=0.0.1-dev \
            --docker . \
            --docker-from=azul/zulu-openjdk-alpine:24-jre-headless-latest \
            --docker-image-repository=ghcr.io/otobrglez/discodigg \
            --docker-image-tag=0.0.1-dev